#!/bin/bash 


IMAGES_EXISTS=$(docker images | grep -i empty)

sudo umount ./stage1/dev  2> /dev/null 
sudo umount ./stage1/proc 2> /dev/null

if [[ -z $IMAGES_EXISTS ]] ; then 
	tar -cf empty.tar -T /dev/null 
	docker build . -t empty.tar 
fi 

docker build . -t jos:latest

if [ -f empty.tar ] ; then 
	rm empty.tar 
fi
