#!/bin/bash 


IMAGES_EXISTS=$(docker images | grep -i empty)

sudo umount ./stage1/dev  2> /dev/null 
sudo umount ./stage1/proc 2> /dev/null

if [[ -z $IMAGES_EXISTS ]] ; then 
  echo "Create empty docker image"
	tar -cf empty.tar -T /dev/null 
	docker import empty.tar empty:latest
fi 

docker build . -t mah454/jos:latest

if [ -f empty.tar ] ; then 
	rm empty.tar 
fi
