#!/bin/bash 

. ./init-script 

FILE_NAME="disk.img"

echo "[*] Activate qemu nbd"
sudo modprobe nbd 
qemu-img create -f qcow2 disk.img 300M > /dev/null
# qemu-img create -f qcow2 $FILE_NAME 256M > /dev/null
sudo qemu-nbd -c /dev/nbd0 $FILE_NAME

echo "[*] Partition disk and format ext4" 
(
echo o 
echo n
echo p 
echo 1
echo 
echo 
echo w
) | sudo fdisk /dev/nbd0 > /dev/null 2>&1

sudo mkfs.ext4 /dev/nbd0p1 > /dev/null 2>&1

echo "[*] Mount filesystems" 
sudo mount /dev/nbd0p1 /mnt/

echo "[*] Copy rootfs" 
sudo cp -aRf stage1/* /mnt/
sudo mkdir /mnt/boot
sudo cp image/boot/vmlinuz /mnt/boot/ 

echo "[*] Install grub"
sudo grub-install --root-directory /mnt/ /dev/nbd0 > /dev/null 2>&1
sudo cp grub.cfg /mnt/boot/grub/

echo "[*] Disconnect nbd" 
sudo umount /mnt 
sudo qemu-nbd -d /dev/nbd0 > /dev/null
