#!/bin/bash 

JOS_PROJECT_DIR="$HOME/JOS_Project"

sudo umount /mnt > /dev/null 2>&1
sudo qemu-nbd -d /dev/nbd0 > /dev/null 2>&1

sudo umount stage1/dev 2> /dev/null 
sudo umount stage1/proc 2> /dev/null
sudo umount stage1/sys 2> /dev/null

echo "[*] Initialize "
sudo rm -rf image stage1 2> /dev/null 
mkdir -p image/boot/ stage1 2> /dev/null  
mkdir -p stage1/modules/{available,enabled}
mkdir -p stage1/tmp stage1/proc stage1/dev stage1/sys stage1/etc

echo "[*] Copy files"
cp $JOS_PROJECT_DIR/kernel/linux-5.17.6/arch/x86_64/boot/bzImage	image/boot/vmlinuz 
cp /usr/lib/ISOLINUX/isolinux.bin					image/boot/ 
cp isolinux.cfg								image/
cp /usr/lib/syslinux/modules/bios/ldlinux.c32				image/
cp $JOS_PROJECT_DIR/init/target/x86_64-unknown-linux-musl/release/init	stage1/init  

echo "[*] Copy jre and jos-engine" 
cp -aRf jre								stage1/ 
cp -aRf $JOS_PROJECT_DIR/jos-engine/jos-core/target/lib/		stage1/engine/
cp -aRf $JOS_PROJECT_DIR/jos-engine/etc/*				stage1/etc/

echo "[*] Fix dependencies" 
./fix_dependencies

sudo chown root:root -R stage1 

echo "[*] Activate qemu nbd"
sudo modprobe nbd 
qemu-img create -f qcow2 disk.img 256M > /dev/null
sudo qemu-nbd -c /dev/nbd0 disk.img 

echo "[*] Partition disk and format ext4" 
(
echo o 
echo n
echo p 
echo 1
echo 
echo 
echo w
) | sudo fdisk /dev/nbd0 > /dev/null 2>&1

sudo mkfs.ext4 /dev/nbd0p1 > /dev/null 2>&1

echo "[*] Mount filesystems" 
sudo mount /dev/nbd0p1 /mnt/

echo "[*] Copy rootfs" 
sudo cp -aRf stage1/* /mnt/
sudo mkdir /mnt/boot
sudo cp image/boot/vmlinuz /mnt/boot/ 

echo "[*] Install grub"
sudo grub-install --root-directory /mnt/ /dev/nbd0 > /dev/null 2>&1
sudo cp grub.cfg /mnt/boot/grub/

echo "[*] Disconnect nbd" 
sudo umount /mnt 
sudo qemu-nbd -d /dev/nbd0 > /dev/null
